### ISSUE TITLE
The Shapes of CSS

### ISSUE THREAD

**Issue by HaveF** [HaveF/havef.github.com#22]
[The Shapes of CSS](https://css-tricks.com/examples/ShapesOfCSS/)

# 圆/椭圆
你要是理解border-radius的含义了，那么圆形和椭圆就应该没啥问题了。只不过椭圆需要再算算如何才能画出你想要的指定a/b的那种椭圆
![sc-2015-12-3_15_11_56](https://cloud.githubusercontent.com/assets/54462/11554160/7358935e-99d0-11e5-834b-8bf9adfd556d.png)
![sc-2015-12-3_15_12_10](https://cloud.githubusercontent.com/assets/54462/11554161/736b0570-99d0-11e5-8349-cc5e6ca7863d.png)

# 各种箭头
这个需要准确理解盒子模型中的border-top/bottom/left/right，能想明白各个边的接口/榫子，再脑补联想下，各种箭头的画法也就没有问题了
  ```css
#s {
	width: 100px;
	height: 100px;
	border-left: 30px solid ;
	border-right: 30px solid blue;
	border-bottom: 30px solid red;
	border-top: 30px solid red;
}
  ```
![sc-2015-12-3_15_16_57](https://cloud.githubusercontent.com/assets/54462/11554205/e6d7c962-99d0-11e5-886f-196f5d2ffccb.png)
比如下箭头就是（对应这上面榫子图想，最简单的方法就是看斜边）
![sc-2015-12-3_15_17_58](https://cloud.githubusercontent.com/assets/54462/11554220/0a2f0dee-99d1-11e5-94ba-2208d3797bda.png)
  ```css
#triangle-down {
	width: 0;
	height: 0;
	border-left: 50px solid transparent;
	border-right: 50px solid transparent;
	border-top: 100px solid red;
}
  ```
再比如这种三角形
![sc-2015-12-3_15_19_18](https://cloud.githubusercontent.com/assets/54462/11554252/475e8be0-99d1-11e5-8a35-cbb65dbda6f3.png)
可以
  ```css
#triangle-topleft {
    width: 0;
    height: 0;
    border-top: 100px solid red;
    border-right: 100px solid transparent;
}
  ```
也可以写成
  ```css
#triangle-topleft {
    width: 0;
    height: 0;
    border-left: 100px solid red;
    border-bottom: 100px solid transparent;
}
  ```
因为你想，楔子那图只有左下和右上两个斜边可以和目标图形中的斜边搭配，所以就有这两种写法了

其它的鬼暂时还没有太多时间去研究
