### ISSUE TITLE
float & clear in CSS

### ISSUE THREAD

**Issue by HaveF** [HaveF/havef.github.com#24]
当一个元素成为浮动元素之后，它就脱离了文档流，父元素看不到它，自然也不会包围它。不包围时，会出现一些问题，比如
![sc-2015-12-11_8_19_05](https://cloud.githubusercontent.com/assets/54462/11732541/2f736d9c-9fe0-11e5-95c0-c675b0b12e98.png)
在这样一个布局中
```html
<section>
  <img src="images/rubber_duck.jpg">
  <p>It's fun to float.</p>
</section>
<footer>Here is the footer element that runs across the bottom of the page. </footer>
```
```css
section {border:1px solid blue; margin:0 0 10px 0;}
img {float:left;}
footer {font-family:Helvetica, Arial, sans-serif; font-size:1em; border:1px solid red;}
p {font-family:Helvetica, Arial, sans-serif; font-size:1em; margin:0;}
```
`footer`本来是应该在`section`下面出现的，但`img`变成浮动元素之后，脱离了`section`，后面的`footer`就跟着前一个块级元素`section`后面，出现了错误的布局。

而解决这种问题有三种方案：
* 为父元素添加`overflow: hidden`强制包含浮动元素
   - 但这其实应该算是这种语法的一个副作用，它的主要作用是防止父元素被包含的超大元素给撑开。
   - 另外这种方法必须得有父元素才行
* 同时浮动父元素
  - 但同时需要设置父元素的`width:100%`否则父元素会收缩包裹自元素
  - 另外`footer`也需要`clear:left`
  - 这种方法也需要有父元素才行
* 用`.clearfix:after`这种方式
  ```css
.clearfix:after{
  content:'.';
  display:block;
  height:0;
  visibility:hidden;
  clear:both
}

  ```
  - 一共有五项，一项内容，一项block，两项0,hidden，一项clear，很好记
  - 这种方式可以没有父元素
