### ISSUE TITLE
image-map in html (map, area tag)

### ISSUE THREAD

**Issue by HaveF** [HaveF/havef.github.com#51]
# image-map 101
An image-map, with clickable areas:

```html
<img src ="planets.gif" width="145" height="126" alt="Planets"
usemap="#planetmap">

<map name="planetmap">
  <area shape="rect" coords="0,0,82,126" href="sun.htm" alt="Sun">
  <area shape="circle" coords="90,58,3" href="mercur.htm" alt="Mercury">
  <area shape="circle" coords="124,58,8" href="venus.htm" alt="Venus">
</map>
```

主要就是把上面usemap中的#planetmap和下面的map关联起来就行，但主要问题是
**area**，要是矩形，圆形还好说-----但其实在实际使用中根本不可能，需要做的一般
可能都是`poly`，所以怎么把原图中的需要的坐标点标出来，找出来那就是一个重要的问题了

# 如何标记poly的坐标点？
## 如果不是特别复杂
最快的方法应该是一些在线的方法，比如
* [Easy IMAGEMAP Generator](http://imagemap-generator.dariodomi.de/)

TODO;

# 已经得到各种shape之后
## css only
如果展示区域不多，那么可以[只使用css达到效果](http://stackoverflow.com/questions/1896015/highlight-a-section-of-an-image-in-javascript)，大致看一下css就能猜到是怎么处理的了

```css
#image { 
    position: relative; 
    width: 400px;
    height: 100px; 
    background-image: url(image_map.png); 
}

#map-part { 
    position: absolute; 
    top: 10px; 
    left: 10px; 
    width: 50px; 
    height: 50px; 
    background-color: transparent;  
}   

#map-part:hover { 
    background-color: yellow;           /* Yellow Highlight On Hover */
    opacity: 0.2;
    filter: alpha(opacity=20);      
}
```

## 库,,,,,如果你对shape有更多的需求
如果你已经有了shape，那么如果想做一些交互---一些复杂的交互，比如同时要选取很多个区域，用现成的库，比如[mapper.js](http://www.netzgesta.de/mapper/)会方便一些(去看一下其中的例子就能明白他能做什么),,,,当然，本质上它就是在处理`hover`或移出那一块区域的时候对应的class做了什么变化，这是一个很普遍的需求，估计也会有一些其它类型的map库
